### ISSUE TITLE
Resets permissions

### ISSUE THREAD

**Issue by gerroon** [Magisk-Modules-Repo/MagicGApps#10]
Hi 

Is it normal that all app permissions are  resetted after installing or disabling this addon on Lineageos 14.1 with Magisk 16.7 , Gapps-Pico?

**Comment by VR-25** [comment]
The same happens when you flash GApps the regular way (without this module). I'm investigating ways to bypass this. Thanks.

**Comment by gerroon** [comment]
thanks
