### ISSUE TITLE
i9300 couldn't bind-mount /persist

### ISSUE THREAD

**Issue by fish47** [Magisk-Modules-Repo/MagicGApps#4]
Since i9300(LineageOS-14.1) in twrp recovery(3.1.1-0) mode doesn't have `/persist` partition, bind-mounting it will raise error.
Here's the `/etc/fstab` content:
```
/dev/block/mmcblk0p3 /efs ext4 rw 0 0
/dev/block/mmcblk0p8 /cache ext4 rw 0 0
/dev/block/mmcblk0p9 /system ext4 rw 0 0
/dev/block/mmcblk0p12 /data ext4 rw 0 0
/dev/block/mmcblk0p10 /preload ext4 rw 0 0
/dev/block/mmcblk1p1 /external_sd exfat rw 0 0
/usb-otg vfat rw 0 0
```

**Comment by hacker1024** [comment]
I have this issue as well, on my Xiaomi Mi 5s Plus (natrium).

**Comment by zhkailing** [comment]
same issue, Latest commit 4870f38  on 2 Nov 2017 works well

**Comment by ayanamist** [comment]
same issue, but i mkdir /persist by myself, and it works now.

**Comment by felipe-francisco-rosa** [comment]
Passing trought the same problem, I have downloaded an older commit and it has worked to me following these steps:

https://github.com/Magisk-Modules-Repo/MagicGApps/tree/25276f3c4a542f58d594d807ffc7d30d1227fbb4

Download or clone -> Download zip

Open the downloaded file and cut all files to main zip archive.

Then delete folder MagicGApps-25276f3c4a542f58d594d807ffc7d30d1227fbb4 (that is now empt)

Execute the zip in TWRP

**Comment by WordlessEcho** [comment]
I9505 same here.

**Comment by bam80** [comment]
@fish47 it doesn't related to i9300

**Comment by bam80** [comment]
>same issue, but i mkdir /persist by myself, and it works now.

Has anyone success on this? Seems doesn't help for me

**Comment by gerroon** [comment]
I have the same issue.

**Comment by Houiin** [comment]
I mkdir /persist by myself, and it works . But there was some problem that make me stuck in boot screen

**Comment by gerroon** [comment]
It seems like there was an update today, claim to fix this I have not tried it myself yet.

**Comment by paolovador** [comment]
The update of 2 days ago finally allowed me to get all of Gapps on my OnePlus 5T OxygenOS 5.1.3.
Great work thanks !! Keep it up !

**Comment by gerroon** [comment]
@paolovador do you get app cache rebuilding everytime you restart your device?

**Comment by paolovador** [comment]
@gerroon I've just done the flash. Could you give me steps to reproduce your problem ? I'll check right away

**Comment by gerroon** [comment]
See the last messages
https://forum.xda-developers.com/apps/magisk/module-systemless-beansgapps-mini-7-1-x-t3611362/post77169395#post77169395

**Comment by paolovador** [comment]
@gerroon permissions are fine after a reboot. No Google play services crashes yet. Everything smooth. I'll keep an eye and let you know

**Comment by gerroon** [comment]
@paolovador thanks keep us updated

**Comment by bam80** [comment]
@paolovador please try to disable migicGapps module, reboot and then look at the permissions of your apps - they should be reset

**Comment by paolovador** [comment]
@bam80 ok I just disabled magiskGapps module, rebooted: all my permissions look fine. I just lost pixel icons, pixel launcher, and Google dialer
![screenshot_20180727-065354](https://user-images.githubusercontent.com/6412153/43302492-2442b0b6-916b-11e8-8c8f-36e07f75fc7d.jpg)

**Comment by paolovador** [comment]
@bam80 after re-enabling the module, Google dialer and pixel launcher came back but their permissions were effectively lost.

**Comment by bam80** [comment]
Thank you @paolovador for the tests. For me it seems permissions lost after disabling the module. 
I wonder if https://github.com/Magisk-Modules-Repo/MagicGApps/issues/3#issuecomment-386544652 solution solves all the problems

**Comment by VR-25** [comment]
The bind-mount issue has been fixed. I'll push a new build in a few days. Thanks for all the reports!
