### ISSUE TITLE
resizing is excessive

### ISSUE THREAD

**Issue by bam80** [Magisk-Modules-Repo/MagicGApps#8]
https://github.com/Magisk-Modules-Repo/MagicGApps/blob/a84865b3db2f125edc6b7e1f0ec0fb7b86fa31fd/META-INF/com/google/android/update-binary#L471
I suppose there is need to resize on 2Gb every time we need more space (pico Gapps need only 128Mb).
Moreover, there may be no free 2Gb on device.
Following formula may be more appropriate for size to resize:
$curUsedM + $reqSizeM

**Comment by VR-25** [comment]
The extra size doesn't occupy space until it's actually filled up. For the same reason, resizing doesn't take any time at all and strict size calculations are unnecessary. 2GB is plenty to accommodate even the largest GApps installation without issues. In the end, if there's extra space, the image is automatically shrunk -- which, again, doesn't take any time at all.

**Comment by bam80** [comment]
This huge resize was the reason of script error on my phone.
FS of the image became corrupted after resize. Not sure if it kernel bug or something else.
I had to manually resize to a smaller size, then script could continue.
Think I could reproduce the problem if script still resizes to a such amount
